# High-capacity configuration tuned for A100 (80GB) GPUs
# Copy or reference this file when running on large GPU instances.
dpi: 300
min_confidence: 0.65
fallback_confidence: 0.3
tmp_dir: tmp
schema_path: configs/resume_schema.json
prompt_template_path: configs/prompts/resume_extraction.txt
skill_taxonomy_path: configs/skills_taxonomy.json
enable_layout_analysis: true
enable_icon_mapping: true

enable_preprocessing: false

ocr:
  lang: en
  engine: paddle
  enable_angle_cls: true
  cls_batch_num: 64
  rec_batch_num: 16
  model_root: ~/.paddlex/official_models
  cpu_threads: 8
  use_gpu: true
  gpu_id: 0
  model_variant: server
  use_doc_orientation_classify: false
  use_doc_unwarping: false
  use_doc_preprocessor: false

llm:
  endpoint: http://127.0.0.1:11434/v1/chat/completions
  api_key_env: LLM_API_KEY
  model: gemma3:27b
  temperature: 0.0
  timeout_seconds: 300
  max_retries: 3
  request_mode: chat-completions
  system_prompt: |
    You are an expert resume parsing assistant. Use the user's prompt to extract resume information as strict JSON.
  enforce_json: true
